--- 
 - name: runing gameoflife
   hosts: all
   become: yes
   tasks:
    - name: installing java and tomcat
      ansible.builtin.apt:
       name: 
         - openjdk-8-jdk
         - tomcat9
    - name: getting war file
      ansible.builtin.get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/gameoflife.war
        dest:  /var/lib/tomcat9/webapps/
    - name: restart tomcat
      ansible.builtin.service:
        name: tomcat9
        state: restarted