--- 
- name: installing nginx
  become: yes
  hosts: all
  tasks:
    - name: update and install nginx
      ansible.builtin.apt:
         name: nginx
         update_cache: yes
         state: present